# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'german_classifier.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.main_tab = QtWidgets.QWidget()
        self.main_tab.setObjectName("main_tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.main_tab)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.main_tab)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(48)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(38, 38, 38);\n"
"color: rgb(255, 255, 255);\n"
"padding: 30px;\n"
"border: none;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setIndent(0)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(20, 122, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.word_edit = QtWidgets.QLineEdit(self.main_tab)
        self.word_edit.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.word_edit.setFont(font)
        self.word_edit.setText("")
        self.word_edit.setObjectName("word_edit")
        self.verticalLayout_7.addWidget(self.word_edit)
        self.class_combo = QtWidgets.QComboBox(self.main_tab)
        self.class_combo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.class_combo.setObjectName("class_combo")
        self.class_combo.addItem("")
        self.class_combo.addItem("")
        self.class_combo.addItem("")
        self.class_combo.addItem("")
        self.class_combo.addItem("")
        self.verticalLayout_7.addWidget(self.class_combo)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.submit_button = QtWidgets.QPushButton(self.main_tab)
        self.submit_button.setStyleSheet("background-color: rgb(42, 42, 42);\n"
"color: rgb(255, 255, 255);")
        self.submit_button.setObjectName("submit_button")
        self.horizontalLayout.addWidget(self.submit_button)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 122, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem5)
        self.tabWidget.addTab(self.main_tab, "")
        self.articles_tab = QtWidgets.QWidget()
        self.articles_tab.setObjectName("articles_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.articles_tab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.articles_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: crimson;\n"
"text-decoration: underline;")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.articles_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("text-decoration: underline;\n"
"color: rgb(255, 85, 0);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.articles_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("text-decoration: underline;\n"
"color: rgb(0, 85, 127);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.splitter = QtWidgets.QSplitter(self.articles_tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.die_list = QtWidgets.QListWidget(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setItalic(True)
        self.die_list.setFont(font)
        self.die_list.setStyleSheet("color: crimson;")
        self.die_list.setObjectName("die_list")
        item = QtWidgets.QListWidgetItem()
        self.die_list.addItem(item)
        self.das_list = QtWidgets.QListWidget(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setItalic(True)
        self.das_list.setFont(font)
        self.das_list.setStyleSheet("color: rgb(66, 141, 77);\n"
"color: rgb(255, 85, 0);")
        self.das_list.setObjectName("das_list")
        item = QtWidgets.QListWidgetItem()
        self.das_list.addItem(item)
        self.der_list = QtWidgets.QListWidget(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setItalic(True)
        self.der_list.setFont(font)
        self.der_list.setStyleSheet("color: rgb(0, 85, 127);")
        self.der_list.setObjectName("der_list")
        item = QtWidgets.QListWidgetItem()
        self.der_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.der_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.der_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.der_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.der_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.der_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.der_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.der_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.der_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.der_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.der_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.der_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.der_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.der_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.der_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.der_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.der_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.der_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.der_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.der_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.der_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.der_list.addItem(item)
        self.verticalLayout.addWidget(self.splitter)
        self.verticalLayout.setStretch(1, 1)
        self.tabWidget.addTab(self.articles_tab, "")
        self.animals_tab = QtWidgets.QWidget()
        self.animals_tab.setObjectName("animals_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.animals_tab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.animal_list = QtWidgets.QListWidget(self.animals_tab)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setItalic(False)
        self.animal_list.setFont(font)
        self.animal_list.setProperty("isWrapping", True)
        self.animal_list.setObjectName("animal_list")
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.animal_list.addItem(item)
        self.verticalLayout_4.addWidget(self.animal_list)
        self.tabWidget.addTab(self.animals_tab, "")
        self.vegetabls_tab = QtWidgets.QWidget()
        self.vegetabls_tab.setObjectName("vegetabls_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.vegetabls_tab)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.vegetable_list = QtWidgets.QListWidget(self.vegetabls_tab)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setItalic(False)
        self.vegetable_list.setFont(font)
        self.vegetable_list.setProperty("isWrapping", True)
        self.vegetable_list.setObjectName("vegetable_list")
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vegetable_list.addItem(item)
        self.verticalLayout_5.addWidget(self.vegetable_list)
        self.tabWidget.addTab(self.vegetabls_tab, "")
        self.simple_tab = QtWidgets.QWidget()
        self.simple_tab.setObjectName("simple_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.simple_tab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.simple_list = QtWidgets.QListWidget(self.simple_tab)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setItalic(False)
        self.simple_list.setFont(font)
        self.simple_list.setProperty("isWrapping", True)
        self.simple_list.setObjectName("simple_list")
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.simple_list.addItem(item)
        self.verticalLayout_2.addWidget(self.simple_list)
        self.tabWidget.addTab(self.simple_tab, "")
        self.phrasal_tab = QtWidgets.QWidget()
        self.phrasal_tab.setObjectName("phrasal_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.phrasal_tab)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.phrasal_list = QtWidgets.QListWidget(self.phrasal_tab)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setItalic(False)
        self.phrasal_list.setFont(font)
        self.phrasal_list.setProperty("isWrapping", True)
        self.phrasal_list.setObjectName("phrasal_list")
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.phrasal_list.addItem(item)
        self.verticalLayout_6.addWidget(self.phrasal_list)
        self.tabWidget.addTab(self.phrasal_tab, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.class_combo.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "German Classifier"))
        self.class_combo.setItemText(0, _translate("MainWindow", "Articles"))
        self.class_combo.setItemText(1, _translate("MainWindow", "Animals"))
        self.class_combo.setItemText(2, _translate("MainWindow", "Vegetabls"))
        self.class_combo.setItemText(3, _translate("MainWindow", "Simple Verbs"))
        self.class_combo.setItemText(4, _translate("MainWindow", "Phrasal Verbs"))
        self.submit_button.setText(_translate("MainWindow", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main_tab), _translate("MainWindow", "main"))
        self.label.setText(_translate("MainWindow", "Die"))
        self.label_2.setText(_translate("MainWindow", "Das"))
        self.label_3.setText(_translate("MainWindow", "Der"))
        __sortingEnabled = self.die_list.isSortingEnabled()
        self.die_list.setSortingEnabled(False)
        item = self.die_list.item(0)
        item.setText(_translate("MainWindow", "der Mann"))
        self.die_list.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.das_list.isSortingEnabled()
        self.das_list.setSortingEnabled(False)
        item = self.das_list.item(0)
        item.setText(_translate("MainWindow", "das Benzin"))
        self.das_list.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.der_list.isSortingEnabled()
        self.der_list.setSortingEnabled(False)
        item = self.der_list.item(0)
        item.setText(_translate("MainWindow", "der Vater"))
        item = self.der_list.item(1)
        item.setText(_translate("MainWindow", "der Junge"))
        item = self.der_list.item(2)
        item.setText(_translate("MainWindow", "der Stier"))
        item = self.der_list.item(3)
        item.setText(_translate("MainWindow", "der Mann"))
        item = self.der_list.item(4)
        item.setText(_translate("MainWindow", "der Mann"))
        item = self.der_list.item(5)
        item.setText(_translate("MainWindow", "der Mann"))
        item = self.der_list.item(6)
        item.setText(_translate("MainWindow", "der Mann"))
        item = self.der_list.item(7)
        item.setText(_translate("MainWindow", "der Mann"))
        item = self.der_list.item(8)
        item.setText(_translate("MainWindow", "der Mann"))
        item = self.der_list.item(9)
        item.setText(_translate("MainWindow", "der Mann"))
        item = self.der_list.item(10)
        item.setText(_translate("MainWindow", "der Mann"))
        item = self.der_list.item(11)
        item.setText(_translate("MainWindow", "der Mann"))
        item = self.der_list.item(12)
        item.setText(_translate("MainWindow", "der Mann"))
        item = self.der_list.item(13)
        item.setText(_translate("MainWindow", "der Mann"))
        item = self.der_list.item(14)
        item.setText(_translate("MainWindow", "der Mann"))
        item = self.der_list.item(15)
        item.setText(_translate("MainWindow", "der Mann"))
        item = self.der_list.item(16)
        item.setText(_translate("MainWindow", "der Mann"))
        item = self.der_list.item(17)
        item.setText(_translate("MainWindow", "der Mann"))
        item = self.der_list.item(18)
        item.setText(_translate("MainWindow", "der Mann"))
        item = self.der_list.item(19)
        item.setText(_translate("MainWindow", "der Mann"))
        item = self.der_list.item(20)
        item.setText(_translate("MainWindow", "der Mann"))
        item = self.der_list.item(21)
        item.setText(_translate("MainWindow", "der Mann"))
        self.der_list.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.articles_tab), _translate("MainWindow", "Articles"))
        __sortingEnabled = self.animal_list.isSortingEnabled()
        self.animal_list.setSortingEnabled(False)
        item = self.animal_list.item(0)
        item.setText(_translate("MainWindow", "isdilf"))
        item = self.animal_list.item(1)
        item.setText(_translate("MainWindow", "sdlkjfljs"))
        item = self.animal_list.item(2)
        item.setText(_translate("MainWindow", "sdl"))
        item = self.animal_list.item(3)
        item.setText(_translate("MainWindow", "jlsdkjlf"))
        item = self.animal_list.item(4)
        item.setText(_translate("MainWindow", "sjlj"))
        item = self.animal_list.item(5)
        item.setText(_translate("MainWindow", "lsjd"))
        item = self.animal_list.item(6)
        item.setText(_translate("MainWindow", "j"))
        item = self.animal_list.item(7)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.animal_list.item(8)
        item.setText(_translate("MainWindow", "lksdjlkj"))
        item = self.animal_list.item(9)
        item.setText(_translate("MainWindow", "sdljf"))
        item = self.animal_list.item(10)
        item.setText(_translate("MainWindow", "ljsl/k"))
        item = self.animal_list.item(11)
        item.setText(_translate("MainWindow", "lk"))
        item = self.animal_list.item(12)
        item.setText(_translate("MainWindow", "jsdljl"))
        item = self.animal_list.item(13)
        item.setText(_translate("MainWindow", "kjsd"))
        item = self.animal_list.item(14)
        item.setText(_translate("MainWindow", "kjlksd"))
        item = self.animal_list.item(15)
        item.setText(_translate("MainWindow", "jl/kj"))
        item = self.animal_list.item(16)
        item.setText(_translate("MainWindow", "lsdj"))
        item = self.animal_list.item(17)
        item.setText(_translate("MainWindow", "lj"))
        item = self.animal_list.item(18)
        item.setText(_translate("MainWindow", ".j"))
        item = self.animal_list.item(19)
        item.setText(_translate("MainWindow", "kj"))
        item = self.animal_list.item(20)
        item.setText(_translate("MainWindow", "klsdjf"))
        item = self.animal_list.item(21)
        item.setText(_translate("MainWindow", "/lsdj"))
        item = self.animal_list.item(22)
        item.setText(_translate("MainWindow", "lfkjsd/lk"))
        item = self.animal_list.item(23)
        item.setText(_translate("MainWindow", "jfkj"))
        item = self.animal_list.item(24)
        item.setText(_translate("MainWindow", "/lksjd/"))
        item = self.animal_list.item(25)
        item.setText(_translate("MainWindow", "lkjsd"))
        item = self.animal_list.item(26)
        item.setText(_translate("MainWindow", "lfkjsdkljlk"))
        item = self.animal_list.item(27)
        item.setText(_translate("MainWindow", "sjdk"))
        item = self.animal_list.item(28)
        item.setText(_translate("MainWindow", "js/ks"))
        item = self.animal_list.item(29)
        item.setText(_translate("MainWindow", "dfj.dfskjd;dfjkjdsksja"))
        item = self.animal_list.item(30)
        item.setText(_translate("MainWindow", "jsad"))
        item = self.animal_list.item(31)
        item.setText(_translate("MainWindow", "kjkdsa.j"))
        item = self.animal_list.item(32)
        item.setText(_translate("MainWindow", "dfskj."))
        item = self.animal_list.item(33)
        item.setText(_translate("MainWindow", "sjsadk"))
        item = self.animal_list.item(34)
        item.setText(_translate("MainWindow", "jasdk"))
        item = self.animal_list.item(35)
        item.setText(_translate("MainWindow", "j.kjdsa."))
        item = self.animal_list.item(36)
        item.setText(_translate("MainWindow", "kj"))
        item = self.animal_list.item(37)
        item.setText(_translate("MainWindow", ".ksdjfksdjkfiwejf;WKkK."))
        item = self.animal_list.item(38)
        item.setText(_translate("MainWindow", "KSD?"))
        item = self.animal_list.item(39)
        item.setText(_translate("MainWindow", "k"))
        item = self.animal_list.item(40)
        item.setText(_translate("MainWindow", "M"))
        item = self.animal_list.item(41)
        item.setText(_translate("MainWindow", "K/"))
        item = self.animal_list.item(42)
        item.setText(_translate("MainWindow", "LFKDSAL"))
        item = self.animal_list.item(43)
        item.setText(_translate("MainWindow", "KLSDK"))
        item = self.animal_list.item(44)
        item.setText(_translate("MainWindow", "FNSAD,MF,MSN,"))
        item = self.animal_list.item(45)
        item.setText(_translate("MainWindow", "MVXBCAAH"))
        item = self.animal_list.item(46)
        item.setText(_translate("MainWindow", "LJAS"))
        item = self.animal_list.item(47)
        item.setText(_translate("MainWindow", "JVLJSDLIJ"))
        item = self.animal_list.item(48)
        item.setText(_translate("MainWindow", "LJ"))
        item = self.animal_list.item(49)
        item.setText(_translate("MainWindow", "JSDAL"))
        item = self.animal_list.item(50)
        item.setText(_translate("MainWindow", "KJDSLKJ"))
        item = self.animal_list.item(51)
        item.setText(_translate("MainWindow", "SLK"))
        item = self.animal_list.item(52)
        item.setText(_translate("MainWindow", "JLKJLKJ"))
        item = self.animal_list.item(53)
        item.setText(_translate("MainWindow", "LKJ"))
        item = self.animal_list.item(54)
        item.setText(_translate("MainWindow", "SDLJKJSD"))
        item = self.animal_list.item(55)
        item.setText(_translate("MainWindow", "/LDSJ"))
        item = self.animal_list.item(56)
        item.setText(_translate("MainWindow", "LKSDAJLSDJLKJ"))
        item = self.animal_list.item(57)
        item.setText(_translate("MainWindow", "LK"))
        item = self.animal_list.item(58)
        item.setText(_translate("MainWindow", "KJ"))
        item = self.animal_list.item(59)
        item.setText(_translate("MainWindow", "LSDJLKVJ"))
        item = self.animal_list.item(60)
        item.setText(_translate("MainWindow", "SLDKJSLJ"))
        item = self.animal_list.item(61)
        item.setText(_translate("MainWindow", "LSJ"))
        item = self.animal_list.item(62)
        item.setText(_translate("MainWindow", "/SL"))
        item = self.animal_list.item(63)
        item.setText(_translate("MainWindow", "J/SADLJ"))
        item = self.animal_list.item(64)
        item.setText(_translate("MainWindow", "L/J"))
        item = self.animal_list.item(65)
        item.setText(_translate("MainWindow", "LKJ"))
        item = self.animal_list.item(66)
        item.setText(_translate("MainWindow", "DLSAJ"))
        self.animal_list.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.animals_tab), _translate("MainWindow", "Animals"))
        __sortingEnabled = self.vegetable_list.isSortingEnabled()
        self.vegetable_list.setSortingEnabled(False)
        item = self.vegetable_list.item(0)
        item.setText(_translate("MainWindow", "isdilf"))
        item = self.vegetable_list.item(1)
        item.setText(_translate("MainWindow", "sdlkjfljs"))
        item = self.vegetable_list.item(2)
        item.setText(_translate("MainWindow", "sdl"))
        item = self.vegetable_list.item(3)
        item.setText(_translate("MainWindow", "jlsdkjlf"))
        item = self.vegetable_list.item(4)
        item.setText(_translate("MainWindow", "sjlj"))
        item = self.vegetable_list.item(5)
        item.setText(_translate("MainWindow", "lsjd"))
        item = self.vegetable_list.item(6)
        item.setText(_translate("MainWindow", "j"))
        item = self.vegetable_list.item(7)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.vegetable_list.item(8)
        item.setText(_translate("MainWindow", "lksdjlkj"))
        item = self.vegetable_list.item(9)
        item.setText(_translate("MainWindow", "sdljf"))
        item = self.vegetable_list.item(10)
        item.setText(_translate("MainWindow", "ljsl/k"))
        item = self.vegetable_list.item(11)
        item.setText(_translate("MainWindow", "lk"))
        item = self.vegetable_list.item(12)
        item.setText(_translate("MainWindow", "jsdljl"))
        item = self.vegetable_list.item(13)
        item.setText(_translate("MainWindow", "kjsd"))
        item = self.vegetable_list.item(14)
        item.setText(_translate("MainWindow", "kjlksd"))
        item = self.vegetable_list.item(15)
        item.setText(_translate("MainWindow", "jl/kj"))
        item = self.vegetable_list.item(16)
        item.setText(_translate("MainWindow", "lsdj"))
        item = self.vegetable_list.item(17)
        item.setText(_translate("MainWindow", "lj"))
        item = self.vegetable_list.item(18)
        item.setText(_translate("MainWindow", ".j"))
        item = self.vegetable_list.item(19)
        item.setText(_translate("MainWindow", "kj"))
        item = self.vegetable_list.item(20)
        item.setText(_translate("MainWindow", "klsdjf"))
        item = self.vegetable_list.item(21)
        item.setText(_translate("MainWindow", "/lsdj"))
        item = self.vegetable_list.item(22)
        item.setText(_translate("MainWindow", "lfkjsd/lk"))
        item = self.vegetable_list.item(23)
        item.setText(_translate("MainWindow", "jfkj"))
        item = self.vegetable_list.item(24)
        item.setText(_translate("MainWindow", "/lksjd/"))
        item = self.vegetable_list.item(25)
        item.setText(_translate("MainWindow", "lkjsd"))
        item = self.vegetable_list.item(26)
        item.setText(_translate("MainWindow", "lfkjsdkljlk"))
        item = self.vegetable_list.item(27)
        item.setText(_translate("MainWindow", "sjdk"))
        item = self.vegetable_list.item(28)
        item.setText(_translate("MainWindow", "js/ks"))
        item = self.vegetable_list.item(29)
        item.setText(_translate("MainWindow", "dfj.dfskjd;dfjkjdsksja"))
        item = self.vegetable_list.item(30)
        item.setText(_translate("MainWindow", "jsad"))
        item = self.vegetable_list.item(31)
        item.setText(_translate("MainWindow", "kjkdsa.j"))
        item = self.vegetable_list.item(32)
        item.setText(_translate("MainWindow", "dfskj."))
        item = self.vegetable_list.item(33)
        item.setText(_translate("MainWindow", "sjsadk"))
        item = self.vegetable_list.item(34)
        item.setText(_translate("MainWindow", "jasdk"))
        item = self.vegetable_list.item(35)
        item.setText(_translate("MainWindow", "j.kjdsa."))
        item = self.vegetable_list.item(36)
        item.setText(_translate("MainWindow", "kj"))
        item = self.vegetable_list.item(37)
        item.setText(_translate("MainWindow", ".ksdjfksdjkfiwejf;WKkK."))
        item = self.vegetable_list.item(38)
        item.setText(_translate("MainWindow", "KSD?"))
        item = self.vegetable_list.item(39)
        item.setText(_translate("MainWindow", "k"))
        item = self.vegetable_list.item(40)
        item.setText(_translate("MainWindow", "M"))
        item = self.vegetable_list.item(41)
        item.setText(_translate("MainWindow", "K/"))
        item = self.vegetable_list.item(42)
        item.setText(_translate("MainWindow", "LFKDSAL"))
        item = self.vegetable_list.item(43)
        item.setText(_translate("MainWindow", "KLSDK"))
        item = self.vegetable_list.item(44)
        item.setText(_translate("MainWindow", "FNSAD,MF,MSN,"))
        item = self.vegetable_list.item(45)
        item.setText(_translate("MainWindow", "MVXBCAAH"))
        item = self.vegetable_list.item(46)
        item.setText(_translate("MainWindow", "LJAS"))
        item = self.vegetable_list.item(47)
        item.setText(_translate("MainWindow", "JVLJSDLIJ"))
        item = self.vegetable_list.item(48)
        item.setText(_translate("MainWindow", "LJ"))
        item = self.vegetable_list.item(49)
        item.setText(_translate("MainWindow", "JSDAL"))
        item = self.vegetable_list.item(50)
        item.setText(_translate("MainWindow", "KJDSLKJ"))
        item = self.vegetable_list.item(51)
        item.setText(_translate("MainWindow", "SLK"))
        item = self.vegetable_list.item(52)
        item.setText(_translate("MainWindow", "JLKJLKJ"))
        item = self.vegetable_list.item(53)
        item.setText(_translate("MainWindow", "LKJ"))
        item = self.vegetable_list.item(54)
        item.setText(_translate("MainWindow", "SDLJKJSD"))
        item = self.vegetable_list.item(55)
        item.setText(_translate("MainWindow", "/LDSJ"))
        item = self.vegetable_list.item(56)
        item.setText(_translate("MainWindow", "LKSDAJLSDJLKJ"))
        item = self.vegetable_list.item(57)
        item.setText(_translate("MainWindow", "LK"))
        item = self.vegetable_list.item(58)
        item.setText(_translate("MainWindow", "KJ"))
        item = self.vegetable_list.item(59)
        item.setText(_translate("MainWindow", "LSDJLKVJ"))
        item = self.vegetable_list.item(60)
        item.setText(_translate("MainWindow", "SLDKJSLJ"))
        item = self.vegetable_list.item(61)
        item.setText(_translate("MainWindow", "LSJ"))
        item = self.vegetable_list.item(62)
        item.setText(_translate("MainWindow", "/SL"))
        item = self.vegetable_list.item(63)
        item.setText(_translate("MainWindow", "J/SADLJ"))
        item = self.vegetable_list.item(64)
        item.setText(_translate("MainWindow", "L/J"))
        item = self.vegetable_list.item(65)
        item.setText(_translate("MainWindow", "LKJ"))
        item = self.vegetable_list.item(66)
        item.setText(_translate("MainWindow", "DLSAJ"))
        self.vegetable_list.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.vegetabls_tab), _translate("MainWindow", "Vegetabls"))
        __sortingEnabled = self.simple_list.isSortingEnabled()
        self.simple_list.setSortingEnabled(False)
        item = self.simple_list.item(0)
        item.setText(_translate("MainWindow", "SDFKJD H"))
        item = self.simple_list.item(1)
        item.setText(_translate("MainWindow", "K"))
        item = self.simple_list.item(2)
        item.setText(_translate("MainWindow", "LSK"))
        item = self.simple_list.item(3)
        item.setText(_translate("MainWindow", "LKAL"))
        item = self.simple_list.item(4)
        item.setText(_translate("MainWindow", "L"))
        item = self.simple_list.item(5)
        item.setText(_translate("MainWindow", "ALK"))
        item = self.simple_list.item(6)
        item.setText(_translate("MainWindow", "LK"))
        item = self.simple_list.item(7)
        item.setText(_translate("MainWindow", "L"))
        item = self.simple_list.item(8)
        item.setText(_translate("MainWindow", "LK"))
        item = self.simple_list.item(9)
        item.setText(_translate("MainWindow", "ASLK"))
        item = self.simple_list.item(10)
        item.setText(_translate("MainWindow", "AALNALKSNALSKNLKL"))
        item = self.simple_list.item(11)
        item.setText(_translate("MainWindow", "AKLK"))
        item = self.simple_list.item(12)
        item.setText(_translate("MainWindow", "L"))
        item = self.simple_list.item(13)
        item.setText(_translate("MainWindow", "L"))
        item = self.simple_list.item(14)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.simple_list.item(15)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.simple_list.item(16)
        item.setText(_translate("MainWindow", "NALSKL"))
        item = self.simple_list.item(17)
        item.setText(_translate("MainWindow", "NLAKSNLKNALN"))
        item = self.simple_list.item(18)
        item.setText(_translate("MainWindow", "NNNAKSNLANASLKL"))
        item = self.simple_list.item(19)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.simple_list.item(20)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.simple_list.item(21)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.simple_list.item(22)
        item.setText(_translate("MainWindow", "K"))
        item = self.simple_list.item(23)
        item.setText(_translate("MainWindow", "ASNLKSALKALK"))
        item = self.simple_list.item(24)
        item.setText(_translate("MainWindow", "AL"))
        item = self.simple_list.item(25)
        item.setText(_translate("MainWindow", "AL"))
        item = self.simple_list.item(26)
        item.setText(_translate("MainWindow", "NASLKNAS"))
        item = self.simple_list.item(27)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.simple_list.item(28)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.simple_list.item(29)
        item.setText(_translate("MainWindow", "NNNN"))
        item = self.simple_list.item(30)
        item.setText(_translate("MainWindow", "N"))
        item = self.simple_list.item(31)
        item.setText(_translate("MainWindow", "N"))
        item = self.simple_list.item(32)
        item.setText(_translate("MainWindow", "N"))
        item = self.simple_list.item(33)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.simple_list.item(34)
        item.setText(_translate("MainWindow", "NLK"))
        item = self.simple_list.item(35)
        item.setText(_translate("MainWindow", "JL"))
        item = self.simple_list.item(36)
        item.setText(_translate("MainWindow", "JUL"))
        item = self.simple_list.item(37)
        item.setText(_translate("MainWindow", "J"))
        item = self.simple_list.item(38)
        item.setText(_translate("MainWindow", "J"))
        item = self.simple_list.item(39)
        item.setText(_translate("MainWindow", "LKJ"))
        item = self.simple_list.item(40)
        item.setText(_translate("MainWindow", ";L"))
        item = self.simple_list.item(41)
        item.setText(_translate("MainWindow", "H"))
        item = self.simple_list.item(42)
        item.setText(_translate("MainWindow", "U"))
        item = self.simple_list.item(43)
        item.setText(_translate("MainWindow", "G"))
        item = self.simple_list.item(44)
        item.setText(_translate("MainWindow", "JH"))
        item = self.simple_list.item(45)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.simple_list.item(46)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.simple_list.item(47)
        item.setText(_translate("MainWindow", "\'"))
        item = self.simple_list.item(48)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.simple_list.item(49)
        item.setText(_translate("MainWindow", "\'L"))
        item = self.simple_list.item(50)
        item.setText(_translate("MainWindow", "\'\'"))
        item = self.simple_list.item(51)
        item.setText(_translate("MainWindow", "K;"))
        item = self.simple_list.item(52)
        item.setText(_translate("MainWindow", "K;"))
        item = self.simple_list.item(53)
        item.setText(_translate("MainWindow", "U"))
        item = self.simple_list.item(54)
        item.setText(_translate("MainWindow", "G"))
        item = self.simple_list.item(55)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.simple_list.item(56)
        item.setText(_translate("MainWindow", "T"))
        item = self.simple_list.item(57)
        item.setText(_translate("MainWindow", "T9"))
        item = self.simple_list.item(58)
        item.setText(_translate("MainWindow", "87"))
        item = self.simple_list.item(59)
        item.setText(_translate("MainWindow", "L"))
        item = self.simple_list.item(60)
        item.setText(_translate("MainWindow", "J"))
        item = self.simple_list.item(61)
        item.setText(_translate("MainWindow", "LJ"))
        item = self.simple_list.item(62)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.simple_list.item(63)
        item.setText(_translate("MainWindow", "L\';"))
        item = self.simple_list.item(64)
        item.setText(_translate("MainWindow", "L\'"))
        item = self.simple_list.item(65)
        item.setText(_translate("MainWindow", "LKJ"))
        item = self.simple_list.item(66)
        item.setText(_translate("MainWindow", "LH"))
        item = self.simple_list.item(67)
        item.setText(_translate("MainWindow", "KG"))
        item = self.simple_list.item(68)
        item.setText(_translate("MainWindow", "GF"))
        item = self.simple_list.item(69)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.simple_list.item(70)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.simple_list.item(71)
        item.setText(_translate("MainWindow", "H"))
        item = self.simple_list.item(72)
        item.setText(_translate("MainWindow", "JHJK"))
        item = self.simple_list.item(73)
        item.setText(_translate("MainWindow", "H"))
        item = self.simple_list.item(74)
        item.setText(_translate("MainWindow", "[[O["))
        item = self.simple_list.item(75)
        item.setText(_translate("MainWindow", "00"))
        item = self.simple_list.item(76)
        item.setText(_translate("MainWindow", "-9"))
        item = self.simple_list.item(77)
        item.setText(_translate("MainWindow", "Y"))
        item = self.simple_list.item(78)
        item.setText(_translate("MainWindow", "T"))
        item = self.simple_list.item(79)
        item.setText(_translate("MainWindow", "F"))
        item = self.simple_list.item(80)
        item.setText(_translate("MainWindow", "J"))
        item = self.simple_list.item(81)
        item.setText(_translate("MainWindow", "KL"))
        item = self.simple_list.item(82)
        item.setText(_translate("MainWindow", "J;"))
        item = self.simple_list.item(83)
        item.setText(_translate("MainWindow", "JK;"))
        item = self.simple_list.item(84)
        item.setText(_translate("MainWindow", "K"))
        item = self.simple_list.item(85)
        item.setText(_translate("MainWindow", "K"))
        item = self.simple_list.item(86)
        item.setText(_translate("MainWindow", ";L"))
        item = self.simple_list.item(87)
        item.setText(_translate("MainWindow", "."))
        item = self.simple_list.item(88)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.simple_list.item(89)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.simple_list.item(90)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.simple_list.item(91)
        item.setText(_translate("MainWindow", "JHG"))
        item = self.simple_list.item(92)
        item.setText(_translate("MainWindow", "JF"))
        item = self.simple_list.item(93)
        item.setText(_translate("MainWindow", "GFJ"))
        item = self.simple_list.item(94)
        item.setText(_translate("MainWindow", "JKH"))
        item = self.simple_list.item(95)
        item.setText(_translate("MainWindow", "LJ"))
        item = self.simple_list.item(96)
        item.setText(_translate("MainWindow", ";J"))
        item = self.simple_list.item(97)
        item.setText(_translate("MainWindow", "KLN"))
        item = self.simple_list.item(98)
        item.setText(_translate("MainWindow", "LK"))
        item = self.simple_list.item(99)
        item.setText(_translate("MainWindow", "New Item"))
        self.simple_list.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.simple_tab), _translate("MainWindow", "Simple Verbs"))
        __sortingEnabled = self.phrasal_list.isSortingEnabled()
        self.phrasal_list.setSortingEnabled(False)
        item = self.phrasal_list.item(0)
        item.setText(_translate("MainWindow", "SDFKJD H"))
        item = self.phrasal_list.item(1)
        item.setText(_translate("MainWindow", "K"))
        item = self.phrasal_list.item(2)
        item.setText(_translate("MainWindow", "LSK"))
        item = self.phrasal_list.item(3)
        item.setText(_translate("MainWindow", "LKAL"))
        item = self.phrasal_list.item(4)
        item.setText(_translate("MainWindow", "L"))
        item = self.phrasal_list.item(5)
        item.setText(_translate("MainWindow", "ALK"))
        item = self.phrasal_list.item(6)
        item.setText(_translate("MainWindow", "LK"))
        item = self.phrasal_list.item(7)
        item.setText(_translate("MainWindow", "L"))
        item = self.phrasal_list.item(8)
        item.setText(_translate("MainWindow", "LK"))
        item = self.phrasal_list.item(9)
        item.setText(_translate("MainWindow", "ASLK"))
        item = self.phrasal_list.item(10)
        item.setText(_translate("MainWindow", "AALNALKSNALSKNLKL"))
        item = self.phrasal_list.item(11)
        item.setText(_translate("MainWindow", "AKLK"))
        item = self.phrasal_list.item(12)
        item.setText(_translate("MainWindow", "L"))
        item = self.phrasal_list.item(13)
        item.setText(_translate("MainWindow", "L"))
        item = self.phrasal_list.item(14)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.phrasal_list.item(15)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.phrasal_list.item(16)
        item.setText(_translate("MainWindow", "NALSKL"))
        item = self.phrasal_list.item(17)
        item.setText(_translate("MainWindow", "NLAKSNLKNALN"))
        item = self.phrasal_list.item(18)
        item.setText(_translate("MainWindow", "NNNAKSNLANASLKL"))
        item = self.phrasal_list.item(19)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.phrasal_list.item(20)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.phrasal_list.item(21)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.phrasal_list.item(22)
        item.setText(_translate("MainWindow", "K"))
        item = self.phrasal_list.item(23)
        item.setText(_translate("MainWindow", "ASNLKSALKALK"))
        item = self.phrasal_list.item(24)
        item.setText(_translate("MainWindow", "AL"))
        item = self.phrasal_list.item(25)
        item.setText(_translate("MainWindow", "AL"))
        item = self.phrasal_list.item(26)
        item.setText(_translate("MainWindow", "NASLKNAS"))
        item = self.phrasal_list.item(27)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.phrasal_list.item(28)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.phrasal_list.item(29)
        item.setText(_translate("MainWindow", "NNNN"))
        item = self.phrasal_list.item(30)
        item.setText(_translate("MainWindow", "N"))
        item = self.phrasal_list.item(31)
        item.setText(_translate("MainWindow", "N"))
        item = self.phrasal_list.item(32)
        item.setText(_translate("MainWindow", "N"))
        item = self.phrasal_list.item(33)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.phrasal_list.item(34)
        item.setText(_translate("MainWindow", "NLK"))
        item = self.phrasal_list.item(35)
        item.setText(_translate("MainWindow", "JL"))
        item = self.phrasal_list.item(36)
        item.setText(_translate("MainWindow", "JUL"))
        item = self.phrasal_list.item(37)
        item.setText(_translate("MainWindow", "J"))
        item = self.phrasal_list.item(38)
        item.setText(_translate("MainWindow", "J"))
        item = self.phrasal_list.item(39)
        item.setText(_translate("MainWindow", "LKJ"))
        item = self.phrasal_list.item(40)
        item.setText(_translate("MainWindow", ";L"))
        item = self.phrasal_list.item(41)
        item.setText(_translate("MainWindow", "H"))
        item = self.phrasal_list.item(42)
        item.setText(_translate("MainWindow", "U"))
        item = self.phrasal_list.item(43)
        item.setText(_translate("MainWindow", "G"))
        item = self.phrasal_list.item(44)
        item.setText(_translate("MainWindow", "JH"))
        item = self.phrasal_list.item(45)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.phrasal_list.item(46)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.phrasal_list.item(47)
        item.setText(_translate("MainWindow", "\'"))
        item = self.phrasal_list.item(48)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.phrasal_list.item(49)
        item.setText(_translate("MainWindow", "\'L"))
        item = self.phrasal_list.item(50)
        item.setText(_translate("MainWindow", "\'\'"))
        item = self.phrasal_list.item(51)
        item.setText(_translate("MainWindow", "K;"))
        item = self.phrasal_list.item(52)
        item.setText(_translate("MainWindow", "K;"))
        item = self.phrasal_list.item(53)
        item.setText(_translate("MainWindow", "U"))
        item = self.phrasal_list.item(54)
        item.setText(_translate("MainWindow", "G"))
        item = self.phrasal_list.item(55)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.phrasal_list.item(56)
        item.setText(_translate("MainWindow", "T"))
        item = self.phrasal_list.item(57)
        item.setText(_translate("MainWindow", "T9"))
        item = self.phrasal_list.item(58)
        item.setText(_translate("MainWindow", "87"))
        item = self.phrasal_list.item(59)
        item.setText(_translate("MainWindow", "L"))
        item = self.phrasal_list.item(60)
        item.setText(_translate("MainWindow", "J"))
        item = self.phrasal_list.item(61)
        item.setText(_translate("MainWindow", "LJ"))
        item = self.phrasal_list.item(62)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.phrasal_list.item(63)
        item.setText(_translate("MainWindow", "L\';"))
        item = self.phrasal_list.item(64)
        item.setText(_translate("MainWindow", "L\'"))
        item = self.phrasal_list.item(65)
        item.setText(_translate("MainWindow", "LKJ"))
        item = self.phrasal_list.item(66)
        item.setText(_translate("MainWindow", "LH"))
        item = self.phrasal_list.item(67)
        item.setText(_translate("MainWindow", "KG"))
        item = self.phrasal_list.item(68)
        item.setText(_translate("MainWindow", "GF"))
        item = self.phrasal_list.item(69)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.phrasal_list.item(70)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.phrasal_list.item(71)
        item.setText(_translate("MainWindow", "H"))
        item = self.phrasal_list.item(72)
        item.setText(_translate("MainWindow", "JHJK"))
        item = self.phrasal_list.item(73)
        item.setText(_translate("MainWindow", "H"))
        item = self.phrasal_list.item(74)
        item.setText(_translate("MainWindow", "[[O["))
        item = self.phrasal_list.item(75)
        item.setText(_translate("MainWindow", "00"))
        item = self.phrasal_list.item(76)
        item.setText(_translate("MainWindow", "-9"))
        item = self.phrasal_list.item(77)
        item.setText(_translate("MainWindow", "Y"))
        item = self.phrasal_list.item(78)
        item.setText(_translate("MainWindow", "T"))
        item = self.phrasal_list.item(79)
        item.setText(_translate("MainWindow", "F"))
        item = self.phrasal_list.item(80)
        item.setText(_translate("MainWindow", "J"))
        item = self.phrasal_list.item(81)
        item.setText(_translate("MainWindow", "KL"))
        item = self.phrasal_list.item(82)
        item.setText(_translate("MainWindow", "J;"))
        item = self.phrasal_list.item(83)
        item.setText(_translate("MainWindow", "JK;"))
        item = self.phrasal_list.item(84)
        item.setText(_translate("MainWindow", "K"))
        item = self.phrasal_list.item(85)
        item.setText(_translate("MainWindow", "K"))
        item = self.phrasal_list.item(86)
        item.setText(_translate("MainWindow", ";L"))
        item = self.phrasal_list.item(87)
        item.setText(_translate("MainWindow", "."))
        item = self.phrasal_list.item(88)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.phrasal_list.item(89)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.phrasal_list.item(90)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.phrasal_list.item(91)
        item.setText(_translate("MainWindow", "JHG"))
        item = self.phrasal_list.item(92)
        item.setText(_translate("MainWindow", "JF"))
        item = self.phrasal_list.item(93)
        item.setText(_translate("MainWindow", "GFJ"))
        item = self.phrasal_list.item(94)
        item.setText(_translate("MainWindow", "JKH"))
        item = self.phrasal_list.item(95)
        item.setText(_translate("MainWindow", "LJ"))
        item = self.phrasal_list.item(96)
        item.setText(_translate("MainWindow", ";J"))
        item = self.phrasal_list.item(97)
        item.setText(_translate("MainWindow", "KLN"))
        item = self.phrasal_list.item(98)
        item.setText(_translate("MainWindow", "LK"))
        item = self.phrasal_list.item(99)
        item.setText(_translate("MainWindow", "New Item"))
        self.phrasal_list.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.phrasal_tab), _translate("MainWindow", "Phrasal Verbs"))

